# freecodecamp.org
## Numpy tutorial

In [2]:
import numpy as np
from random import randint

### Extract certain elements from an array

In [14]:
a = np.array([randint(1,100) for i in range(9)])
a = np.reshape(a,(3,3))

Select two first elements from second row and last element of last row.  
Store this elements in a new array

In [19]:
b = [*a[1][0:2],a[2][2]]
# first two elements are take using a slice and then unpacked using `*`
print(b)

[15, 3, 22]


To extract multiple elements from an array, use slice notation, but use a square brackets pair to use multiple indexes  
`a[2]` returns the third element of the array, but `a[ [2,3] ]` return both the third and fourth elements 

In [7]:
a = np.array([25,30,45,50,67,89,124])
b = a[[1,2,3]]  # notice the double square brackets
print(b)


[30 45 50]


In [10]:
print(a)
# returns the type of the elements of a
print(f'{a.dtype} - Default element size is 64 bits')


[ 25  30  45  50  67  89 124]
int64 - Default element size is 64 bits


Create an array especifying the tipe of elements

In [13]:
a = np.array([2,5,7,9], dtype=float)
a.dtype

dtype('float64')

Shape (`.shape -> tuple(rows, cols)`), dimensions (`.ndim` : number of dimensions) and size (`.size` : total number of elements) of an array

In [35]:
a = np.array( [
              [1,2,2],
              [-5,4,7],
              [-1,0,3]
              ])
print(f"The array 'a' has {a.shape[0]} rows and {a.shape[1]} columns. It has "
      f'{a.ndim} dimensions and {a.size} elements.')

The array 'a' has 3 rows and 3 columns. It has 2 dimensions and 9 elements.


Three-dimensional arrays or so called *matrixes*

In [23]:
b = np.array([
    [[2,6,-7],
     [3,-1,4]],

    [[3,16,-2],
     [2,-12,5]]
    ])
print(f"The array 'b' has {b.shape[0]} arrays of {b.shape[1]} rows and ",
      f"{b.shape[2]} columns. It has {a.ndim} dimensions and "
      f"{a.size} elements.")

The array 'b' has 2 arrays of 2 rows and  3 columns. It has 3 dimensions and 12 elements.


Slicing matrixes

In [25]:
# element in row 2, column 3 of the second array of matrix b
b[1][1][2]  # should return 5

5

Reassigning a whole column or row

In [26]:
print(b)

[[[  2   6  -7]
  [  3  -1   4]]

 [[  3  16  -2]
  [  2 -12   5]]]


In [31]:
b[0][1] = [1,1,1]  # replace 2nd row of 1st array
b[1,:,1] = [0,0]  # replace 2nd column of the 2nd array
b[1,1,:] = -5  # replace whole 2nd row of 2nd array with 5's elements
print(b)

[[[ 2  6 -7]
  [ 1  1  1]]

 [[ 3  0 -2]
  [-5 -5 -5]]]


Some statistics methods applied on a matrix or array

In [43]:
a = np.array( [
              [1,2,2],
              [-5,4,7],
              [-1,0,3]
              ])
print(a)
print("The sum of the elements of each row is: ")
# axis=0 --> x axis, axis=1 -->  y axis
# axis = 0 --> iterate through rows
# axis = 1 --> iterate through columns
cols_sum = a.sum(axis=0)  
for i in range(a.shape[0]):
    print(f"Row {i+1}: {cols_sum[i]}")


[[ 1  2  2]
 [-5  4  7]
 [-1  0  3]]
The sum of the elements of each row is: 
Row 1: -5
Row 2: 6
Row 3: 12


In [48]:
a = np.arange(5)
a + 20


array([20, 21, 22, 23, 24])

### Boolean arrays  
A special form of slicing elements of an array, using `True` to return the element corresponding to that position or `False` to omit it.

In [6]:
c = np.arange(6)
print(c)
# we want only the elements in position 0, 3 and 4 
bool_array = [True,False,False,True,True,False]
c[bool_array]

[0 1 2 3 4 5]


array([0, 3, 4])

In the example above, a list with boolean values was used to slice an array. In the following example we filter an array and the result is another array filled with boolean values, depending on whether they fulfill the given condition.

In [15]:
d = np.arange(10)
print(d)
# check if element is odd
odds = (d %2) != 0
print(odds)

[0 1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False  True]


This result can be used to get the actual values that fulfill the condition

In [19]:
print("odd numbers")
print(d[odds])
print("even numbers")
print(d[(d % 2) == 0])

odd numbers
[1 3 5 7 9]
even numbers
[0 2 4 6 8]


Let's create an array filled with random numbers and the select the values that are above the median

In [23]:
random_array = np.random.rand(30)
print(random_array)

[0.98234871 0.08292989 0.58814866 0.52706015 0.64850111 0.76879235
 0.10600642 0.18439408 0.98123795 0.71056822 0.18775989 0.01182089
 0.98697667 0.86872411 0.10992383 0.7310289  0.65150388 0.65300207
 0.00433831 0.19339238 0.62452012 0.32120617 0.54432572 0.22242058
 0.59897226 0.48399792 0.93511664 0.33224271 0.68369024 0.99222272]


AS we can see, `np.random.rand(n)` returns an array of numbers randomly chosen between 0 and 1. To get integers I will round them and transform them into int type using both `np.round_(array)` and `array.astype(new_type)` methods.

In [25]:
sample = random_array * 100
sample = np.round_(sample)
sample = sample.astype(int)
print(sample)

[98  8 59 53 65 77 11 18 98 71 19  1 99 87 11 73 65 65  0 19 62 32 54 22
 60 48 94 33 68 99]


Alternative (and better) way of obtaining an **array of random numbers** using `np.random.randint(low,high, array_shape, dtype=int)`

In [42]:
# create an array (1 row, 30 cols) with random integers ranging from 1 to 100 
sample2 = np.random.randint(1,100,(1,30))
print(sample2)

[[14 98 45 65 65 27 98 12 38 38 82  5 11 19 98 68 88 83 21 65 64 31 15 44
  76 12 74 94 43 61]]


Show and count only the elements which are equal or greater than the median

In [36]:
median = np.median(sample)
# example of boolean array
upper_sample = sample[sample >= np.median(sample)]
print(f"The median of the sample is {median} and there are",
      f"{upper_sample.size} elements.")
print("There they are:")
print(sorted(upper_sample))

The median of the sample is 59.5 and there are 15 elements.
There they are:
[60, 62, 65, 65, 65, 68, 71, 73, 77, 87, 94, 98, 98, 99, 99]


If `and` operator is used when filtering, it throws an exception

In [47]:
upper_sample[((upper_sample % 2) == 0 ) and (upper_sample > 70)]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Boolean operators: `| and`, `~ not`, `& or`

In [49]:
upper_sample[((upper_sample % 2) == 0 ) | (upper_sample > 70)]


array([98, 77, 98, 71, 99, 87, 73, 62, 60, 94, 68, 99])

## Useful Numpy functions

---
### `random` 

In [50]:
np.random.random(size=2)

array([0.03273174, 0.70038691])

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

---
### `arange`

In [ ]:
np.arange(10)

In [ ]:
np.arange(5, 10)

In [ ]:
np.arange(0, 1, .1)

---
### `reshape`

In [ ]:
np.arange(10).reshape(2, 5)

In [ ]:
np.arange(10).reshape(5, 2)

---
### `linspace`

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

---
### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

---
### `identity` and `eye`

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=-3)