# freecodecamp.org
## Numpy tutorial

In [1]:
import numpy as np
from random import randint

### Extract certain elements from an array

In [14]:
a = np.array([randint(1,100) for i in range(9)])
a = np.reshape(a,(3,3))

Select two first elements from second row and last element of last row.  
Store this elements in a new array

In [19]:
b = [*a[1][0:2],a[2][2]]
# first two elements are take using a slice and then unpacked using `*`
print(b)

[15, 3, 22]


To extract multiple elements from an array, use slice notation, but use a square brackets pair to use multiple indexes  
`a[2]` returns the third element of the array, but `a[ [2,3] ]` return both the third and fourth elements 

In [7]:
a = np.array([25,30,45,50,67,89,124])
b = a[[1,2,3]]  # notice the double square brackets
print(b)


[30 45 50]


In [10]:
print(a)
# returns the type of the elements of a
print(f'{a.dtype} - Default element size is 64 bits')


[ 25  30  45  50  67  89 124]
int64 - Default element size is 64 bits


Create an array especifying the tipe of elements

In [13]:
a = np.array([2,5,7,9], dtype=float)
a.dtype

dtype('float64')

Shape (`.shape -> tuple(rows, cols)`), dimensions (`.ndim` : number of dimensions) and size (`.size` : total number of elements) of an array

In [35]:
a = np.array( [
              [1,2,2],
              [-5,4,7],
              [-1,0,3]
              ])
print(f"The array 'a' has {a.shape[0]} rows and {a.shape[1]} columns. It has "
      f'{a.ndim} dimensions and {a.size} elements.')

The array 'a' has 3 rows and 3 columns. It has 2 dimensions and 9 elements.


Three-dimensional arrays or so called *matrixes*

In [23]:
b = np.array([
    [[2,6,-7],
     [3,-1,4]],

    [[3,16,-2],
     [2,-12,5]]
    ])
print(f"The array 'b' has {b.shape[0]} arrays of {b.shape[1]} rows and ",
      f"{b.shape[2]} columns. It has {a.ndim} dimensions and "
      f"{a.size} elements.")

The array 'b' has 2 arrays of 2 rows and  3 columns. It has 3 dimensions and 12 elements.


Slicing matrixes

In [25]:
# element in row 2, column 3 of the second array of matrix b
b[1][1][2]  # should return 5

5

Reassigning a whole column or row

In [26]:
print(b)

[[[  2   6  -7]
  [  3  -1   4]]

 [[  3  16  -2]
  [  2 -12   5]]]


In [31]:
b[0][1] = [1,1,1]  # replace 2nd row of 1st array
b[1,:,1] = [0,0]  # replace 2nd column of the 2nd array
b[1,1,:] = -5  # replace whole 2nd row of 2nd array with 5's elements
print(b)

[[[ 2  6 -7]
  [ 1  1  1]]

 [[ 3  0 -2]
  [-5 -5 -5]]]


Some statistics methods applied on a matrix or array

In [43]:
a = np.array( [
              [1,2,2],
              [-5,4,7],
              [-1,0,3]
              ])
print(a)
print("The sum of the elements of each row is: ")
# axis=0 --> x axis, axis=1 -->  y axis
# axis = 0 --> iterate through rows
# axis = 1 --> iterate through columns
cols_sum = a.sum(axis=0)  
for i in range(a.shape[0]):
    print(f"Row {i+1}: {cols_sum[i]}")


[[ 1  2  2]
 [-5  4  7]
 [-1  0  3]]
The sum of the elements of each row is: 
Row 1: -5
Row 2: 6
Row 3: 12


In [48]:
a = np.arange(5)
a + 20


array([20, 21, 22, 23, 24])