![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [4]:
# your code goes here
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
# your code goes here
np.ones((2,2),dtype=int)  # np.ones(shape, dtype=int)

array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
# your code goes here
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
# your code goes here
X = np.array([[1,2,3],[4,5,6]])
shape = X.shape
dtype = X.dtype
np.ones(shape, dtype = dtype)


array([[1, 1, 1],
       [1, 1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
# your code goes here
np.zeros(shape, dtype = dtype)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [9]:
# your code goes here
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
# your code goes here
print(X)
np.full(X.shape, 7)

[[1 2 3]
 [4 5 6]]


array([[7, 7, 7],
       [7, 7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [11]:
# your code goes here
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [12]:
# your code goes here
np.random.randint(1,10,3)  # start, stop, number of elements --> random integers

array([7, 2, 5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [13]:
# your code goes here
np.random.rand(3,3,3)  # np.random.rand(shape) --> random numbers between 1 and 10

array([[[0.29835346, 0.19694524, 0.57681731],
        [0.18715463, 0.49242823, 0.48709923],
        [0.62373998, 0.6369888 , 0.01711953]],

       [[0.74004541, 0.46607915, 0.33138065],
        [0.61095337, 0.16014655, 0.73718613],
        [0.89190916, 0.4567067 , 0.08767279]],

       [[0.92248516, 0.94610849, 0.23781716],
        [0.85354561, 0.5518228 , 0.89440444],
        [0.33902819, 0.20354526, 0.31112812]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [14]:
# your code goes here
X = [i**2-3 for i in range(1,11) if i % 2 != 2]
Y = np.array(X)
print(f'{Y}, {type(Y)}')

[-2  1  6 13 22 33 46 61 78 97], <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [15]:
# your code goes here
x = np.random.randint(1,10,5)
y = x.copy()
print(f'x: {x}, y: {y}')
x[1] = 12
print('This demonstrate that y is an independent copy of x')
print(f'x: {x}, y: {y}')

x: [4 7 5 6 1], y: [4 7 5 6 1]
This demonstrate that y is an independent copy of x
x: [ 4 12  5  6  1], y: [4 7 5 6 1]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [16]:
# your code goes here
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [17]:
# your code goes here
a = np.arange(1,11)
a[a %2 != 0]

array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [18]:
# your code goes here
np.arange(10,0,-1)  # start, stop, step

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [19]:
# your code goes here
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [20]:
# your code goes here


In [21]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation
Note: array means matrix with only ONE row

### Given the X numpy array, show it's first element

In [22]:
# your code goes here
x = np.array(X)
print(x)
print(f'Size of x is {x.size}. Last element will be removed to reshape it',
      'into a 3x3 matrix.')
x = np.delete(x,-1)
x = x.reshape(3,3)
print(x)
print(f'First element of x is: {x[0,0]}')

[-2  1  6 13 22 33 46 61 78 97]
Size of x is 10. Last element will be removed to reshape it into a 3x3 matrix.
[[-2  1  6]
 [13 22 33]
 [46 61 78]]
First element of x is: -2


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [23]:
# your code goes here
print(x)
print(f'Last element of x is: {x[-1,-1]}')

[[-2  1  6]
 [13 22 33]
 [46 61 78]]
Last element of x is: 78


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [24]:
# your code goes here
x = np.random.randint(1,10,5)
print(x)
x[:3]

[1 9 3 3 6]


array([1, 9, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements (elements between first and last elements)

In [25]:
# your code goes here
print(x)
x[1:-1]

[1 9 3 3 6]


array([9, 3, 3])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [26]:
# your code goes here
print(x)
x[::-1]


[1 9 3 3 6]


array([6, 3, 3, 9, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [27]:
# your code goes here
print(x)
x[::2]


[1 9 3 3 6]


array([1, 3, 6])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [28]:
# your code goes here
m = np.random.randint(10,50,12).reshape(4,3)
print(m)
m[0]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


array([35, 16, 39])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [29]:
# your code goes here
print(m)
m[-1]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


array([22, 46, 19])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [30]:
# your code goes here
print(m)
m[0,0]


[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


35

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [31]:
# your code goes here
print(m)
m[-1,-1]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


19

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [32]:
# your code goes here
print(m)
m[1:-1]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


array([[44, 16, 42],
       [46, 30, 31]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [33]:
# your code goes here
print(m)
m[:2,:2]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


array([[35, 16],
       [44, 16]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [34]:
# your code goes here
print(m)
m[-2:,-2:]  # slice: [before last (-2) --> last ()]

[[35 16 39]
 [44 16 42]
 [46 30 31]
 [22 46 19]]


array([[30, 31],
       [46, 19]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [35]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [36]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [37]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [38]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [39]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [40]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [41]:
# your code goes here


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [42]:
# your code goes here


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [43]:
# your code goes here
m = np.random.randint(-25,25,8)
print(m)
m < 0


[-22  -7  12  -2  -2 -13   3 -20]


array([ True,  True, False,  True,  True,  True, False,  True])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [44]:
# your code goes here
print(m)
m[m < 0]

[-22  -7  12  -2  -2 -13   3 -20]


array([-22,  -7,  -2,  -2, -13, -20])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [45]:
# your code goes here
print(m)
m[m > 5]

[-22  -7  12  -2  -2 -13   3 -20]


array([12])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [46]:
# your code goes here
print(m)
print(f'Mean of array "m" is: {np.mean(a)}')
m[m > np.mean(a)]

[-22  -7  12  -2  -2 -13   3 -20]
Mean of array "m" is: 5.5


array([12])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [47]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[(X == 2) | (X == 10)]  # ~ not, | or, & and


array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [48]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
Y = np.array([-1, 2, 5, -4, 5, 6, 7, -10, -9, 10])
print(f'X: {X}')
print(f'Y: {Y}')
print(f'None of elements in X is zero: {all(X != 0)}')
print(f'None of elements in Y is zero: {all(Y != 0)}')

X: [-1  2  0 -4  5  6  0  0 -9 10]
Y: [ -1   2   5  -4   5   6   7 -10  -9  10]
None of elements in X is zero: False
None of elements in Y is zero: True


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [49]:
# your code goes here
print(X)
print(f'X has at least a zero element in it: {any(X == 0)}')

[-1  2  0 -4  5  6  0  0 -9 10]
X has at least a zero element in it: True


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [50]:
# your code goes here
print(X)
print(f'Sum of all elements of X is {X.sum()}')
# print(f'Sum of all elements of X is {sum(X)}')


[-1  2  0 -4  5  6  0  0 -9 10]
Sum of all elements of X is 9


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [51]:
# your code goes here
print(X)
print(f'Mean of elements of X is {np.mean(X)}')


[-1  2  0 -4  5  6  0  0 -9 10]
Mean of elements of X is 0.9


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [55]:
# your code goes here
x = np.random.randint(-5,10,(4,3))
print(x)
print('Sum of elements in each column:')
print(x.sum(axis=0))  # axis=0 --> x axis, axis=1 --> y axis | (x,y) --> (0,1)

[[ 6 -1  0]
 [ 5  0  5]
 [-4  6 -4]
 [-5 -4 -1]]
Sum of elements in each column:
[2 1 0]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [61]:
# your code goes here
print(x)
means = np.round(x.mean(axis=1),2)
for index, value in enumerate(means):
    print(f'Mean value of row {index}: {value}')

[[ 6 -1  0]
 [ 5  0  5]
 [-4  6 -4]
 [-5 -4 -1]]
Mean value of row 0: 1.67
Mean value of row 1: 3.33
Mean value of row 2: -0.67
Mean value of row 3: -3.33


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [63]:
# your code goes here
print(x)
print(f'Maximum value of elements in matrix "x" is: {x.max()}')

[[ 6 -1  0]
 [ 5  0  5]
 [-4  6 -4]
 [-5 -4 -1]]
Maximum value of elements in matrix "x" is: 6


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)